apiVersion: server/v1
kind: Deployment
metadata:
  name: go-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: raviteja0628/liatrioserver:1.0.0 # Update this line
        ports:
        - containerPort: 8080
